### ISSUE TITLE
TypeError When Running Jest Tests with "@kayahr/jest-electron-runner": "Cannot read properties of undefined (reading 'legacyFakeTimers')"

### ISSUE THREAD

**Issue by Amelia-Mowers** [kayahr/jest-electron-runner#17]
Hello,

I am encountering an issue when using `@kayahr/jest-electron-runner` with Jest. When running my tests, I receive the following error:

```
TypeError: Cannot read properties of undefined (reading 'legacyFakeTimers')
```

This occurs for both main and renderer processes.

The error trace leads back to `jest-runtime` which is a dependency of `@kayahr/jest-electron-runner`. 

Here are my dev dependencies:

```json
"devDependencies": {
  "@kayahr/jest-electron-runner": "^29.5.0",
  "concurrently": "^8.0.1",
  "cross-env": "^7.0.3",
  "electron": "^24.2.0",
  "jest": "^27.5.1",
  "wait-on": "^7.0.1"
}
```

Jest configuration for main process:

```json
{
  "runner": "@kayahr/jest-electron-runner/main",
  "testEnvironment": "node"
}
```

Jest configuration for renderer process:

```json
{
  "runner": "@kayahr/jest-electron-runner",
  "testEnvironment": "@kayahr/jest-electron-runner/environment"
}
```

Full stack trace/error in renderer:

```bash
 FAIL  src/App.test.js
  ● Test suite failed to run                                                                                                                      

      ● Test suite failed to run

        TypeError: Cannot read properties of undefined (reading 'legacyFakeTimers')

          25 | electron_1.ipcRenderer.on("run-test", async (event, testData, workerID) => {
          26 |     try {
        > 27 |         const result = await (0, runTest_1.default)(testData.path, testData.globalConfig, testData.config, (0, resolver_1.getResolver)(testData.config, testData.serializableModuleMap));
             |                        ^
          28 |         electron_1.ipcRenderer.send(workerID, result);
          29 |     }
          30 |     catch (error) {

          at new Runtime (node_modules/jest-runtime/build/index.js:321:56)
          at runTestInternal (node_modules/@kayahr/jest-electron-runner/lib/main/electron/runTest.js:79:21)
          at async runTest (node_modules/@kayahr/jest-electron-runner/lib/main/electron/runTest.js:198:38)
          at async EventEmitter.<anonymous> (file:<MY-PROJECT-ROOT>/node_modules/@kayahr/jest-electron-runner/lib/main/electron/browser_window_injected_code.js:27:24)


      25 | electron_1.ipcRenderer.on("run-test", async (event, testData, workerID) => {
      26 |     try {
    > 27 |         const result = await (0, runTest_1.default)(testData.path, testData.globalConfig, testData.config, (0, resolver_1.getResolver)(testData.config, testData.serializableModuleMap));
         |                        ^
      28 |         electron_1.ipcRenderer.send(workerID, result);
      29 |     }
      30 |     catch (error) {

      at new Runtime (node_modules/jest-runtime/build/index.js:321:56)
      at runTestInternal (node_modules/@kayahr/jest-electron-runner/lib/main/electron/runTest.js:79:21)
      at async runTest (node_modules/@kayahr/jest-electron-runner/lib/main/electron/runTest.js:198:38)
      at async EventEmitter.<anonymous> (file:<MY-PROJECT-ROOT>/node_modules/@kayahr/jest-electron-runner/lib/main/electron/browser_window_injected_code.js:27:24)
```

Any guidance or feedback to help resolve this issue would be greatly appreciated. Thank you.

**Comment by kayahr** [comment]
You have Jest v27 in your dependencies but jest-electron-runner v29 has its own dependency to Jest v29 so you most likely have two different Jest installations in your node_modules which may cause trouble. I see three options:

* Remove the Jest dependency in your package.json so you always use the one which jest-electron-runner needs
* Upgrade your Jest dependency to v29 so NPM can dedupe the dependencies again
* Downgrade jest-electron-runner to v27 if you need to use the old Jest v27 for some reason.

Does this work?

**Comment by Amelia-Mowers** [comment]
Apologies for the delay. Upgrading the Jest dependency to v29 worked. Thank you.
