### ISSUE TITLE
Cannot read properties of undefined (reading 'legacyFakeTimers')

### ISSUE THREAD

**Issue by gorn** [kayahr/jest-electron-runner#26]
I get this error

     Test suite failed to run

        TypeError: Cannot read properties of undefined (reading 'legacyFakeTimers')

          at new Runtime (node_modules/@kayahr/jest-electron-runner/node_modules/jest-runtime/build/index.js:321:56)
          at runTestInternal (node_modules/@kayahr/jest-electron-runner/lib/main/electron/runTest.js:79:21)
          at async runTest (node_modules/@kayahr/jest-electron-runner/lib/main/electron/runTest.js:198:38)
          at async runInNode (node_modules/@kayahr/jest-electron-runner/lib/main/electron/rpc/JestWorkerRPC.js:18:16)

      at new Runtime (node_modules/@kayahr/jest-electron-runner/node_modules/jest-runtime/build/index.js:321:56)
      at runTestInternal (node_modules/@kayahr/jest-electron-runner/lib/main/electron/runTest.js:79:21)
      at async runTest (node_modules/@kayahr/jest-electron-runner/lib/main/electron/runTest.js:198:38)
      at async runInNode (node_modules/@kayahr/jest-electron-runner/lib/main/electron/rpc/JestWorkerRPC.js:18:16)

**Comment by gorn** [comment]
What is the important info I can provice, which would help to track down the reason?

**Comment by gorn** [comment]
this has been repaired by updating jest
